##  Matrix Transposes

Given a matrix $A$:

$$
A = \begin{bmatrix}
1 & 2 & 4 \\
3 & 3 & 1 \\
2 & 1 & 3
\end{bmatrix}
$$

The transpose is:

$$
A^\top = \begin{bmatrix}
1 & 3 & 2 \\
2 & 3 & 1 \\
4 & 1 & 3
\end{bmatrix}
$$

A matrix is symmetric if:
$$
A^\top = A
$$

An important property:
$$
(R^\top R)^\top = R^\top (R^\top)^\top = R^\top R
$$

So $R^\top R$ is always symmetric.

---

##  Permutations

A permutation matrix $P$ swaps rows of $A$.

Example:
$$
P = \begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

Applying permutation:
$$
P A = \text{Matrix } A \text{ with first two rows swapped}
$$

Important property of $P$:
$$
P^{-1} = P^\top
$$

And:
$$
P^\top P = I
$$

---

##  Vector Spaces

- $\mathbb{R}^2$ is the set of all vectors with two real components.
- $\mathbb{R}^n$ is the set of vectors with $n$ real components.


In [1]:
import jax.numpy as jnp

# Example Matrix A
A = jnp.array([[1, 2, 4],
               [3, 3, 1],
               [2, 1, 3]])

# Transpose of A
A_T = A.T

# Check Symmetry
is_symmetric = jnp.array_equal(A, A_T)

print("Matrix A:")
print(A)
print("\nTranspose A^T:")
print(A_T)
print("\nIs A symmetric?", is_symmetric)

# Symmetric matrix example (R^T R is always symmetric)
R = jnp.array([[1, 2],
               [3, 4],
               [5, 6]])

symmetric_matrix = R.T @ R

print("\nR^T R (Always symmetric):")
print(symmetric_matrix)
print("\nTranspose of (R^T R):")
print(symmetric_matrix.T)

# Example of permutation matrix P (swap row 0 and 1)
P = jnp.array([[0, 1, 0],
               [1, 0, 0],
               [0, 0, 1]])

PA = P @ A

print("\nPermutation matrix P:")
print(P)
print("\nP @ A (Rows swapped):")
print(PA)

# Verify P^{-1} = P^T
P_inv = P.T
print("\nP^T (Inverse of P):")
print(P_inv)

print("\nP^T @ P (Should be Identity):")
print(P.T @ P)


Matrix A:
[[1 2 4]
 [3 3 1]
 [2 1 3]]

Transpose A^T:
[[1 3 2]
 [2 3 1]
 [4 1 3]]

Is A symmetric? False

R^T R (Always symmetric):
[[35 44]
 [44 56]]

Transpose of (R^T R):
[[35 44]
 [44 56]]

Permutation matrix P:
[[0 1 0]
 [1 0 0]
 [0 0 1]]

P @ A (Rows swapped):
[[3 3 1]
 [1 2 4]
 [2 1 3]]

P^T (Inverse of P):
[[0 1 0]
 [1 0 0]
 [0 0 1]]

P^T @ P (Should be Identity):
[[1 0 0]
 [0 1 0]
 [0 0 1]]
